name: Release
on: 
  release:

jobs:
  jq:
    name: Lint JSON with JQ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint datafiles
        run: "zip homeassistant.zip -r homeassistant/*"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: homeassistant.zip
          asset_name: homeassistant.zip
          tag: ${{ github.ref }}
          overwrite: true