name: Release
on: 
  release:

jobs:
  jq:
    name: Lint JSON with JQ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: dummy ref
        run: 'echo "9" >> file'
      - name: check ref
        run: |
          if [ ${{ github.ref }} == $(cat file) ]; then
            exit 0
          else
            exit 1
          fi